### PR TITLE
Improve accessibility of theme menu

### PR DESCRIPTION
**Pull request by jakergrossman**
Fixes issue #33

### CODE REVIEW

**Comment by jakergrossman** [comment]
Actually, it now highlights the themes button but pressing enter does nothing. I don't know the best way to solve that  at the immediate moment.

**Comment by Miodec** [comment]
The problem here is that the themes button is just a div with an onclick function attached

**Comment by Miodec** [comment]
You could try and add an 'enter' event listener and if
`document.activeElement` === `the themes button`
then open the themes window.

**Comment by jakergrossman** [comment]
>You could try and add an 'enter' event listener and if ...

@Miodec of course, but having everything accessible via tab is good for accessibility on the sight. If someone wasn’t able to use a mouse, they might be out of luck.

**Pull request merged**
