### PR TITLE
Hold shift while pressing Redo to keep the current word list

### PR DESCRIPTION
**Pull request by briemens**
Based on user request #26 I implemented an easy way to restart a typing test using the same word list by holding `shift` while pressing redo. (Also works when you focus on redo and press `shift`+`enter`)

### CODE REVIEW

**Comment by bwoodruff** [comment]
shift+esc too please? :) 

https://github.com/briano1905/typings/issues/51#issuecomment-565071776

**Comment by briemens** [comment]
@bwoodruff Indeed. If this PR #56 (hold shift to redo the same test) and PR #51 (press escape to restart) both get merged you can do `shift+esc` to restart the current test.

**Comment by briemens** [comment]
@briano1905 Do you want to merge this PR or close it? It's almost 6 months old now.

**Comment by briano1905** [comment]
Sorry for the delay, I've checked the changes and it looks good :)

**Comment by bwoodruff** [comment]
Great! Thank you!

**Pull request merged**
