### PR TITLE
add shortcut to reset the text

### PR DESCRIPTION
**Pull request by mendelmaleh**

### CODE REVIEW

**Comment by mendelmaleh** [comment]
It would be nice too to be able to just press `enter` when completed and starts over, I don't know where that should be in the code tho, I don't know JS that well :man_shrugging:

**Comment by braydonburn** [comment]
Control + enter does not work on linux (alt + enter does)

**Comment by mendelmaleh** [comment]
> Control + enter does not work on linux (alt + enter does)

__It works on my machine__ (Arch Linux), and I was thinking of making a separate PR for that, two button modifiers are kinda cumbersome... Tho I imagine `ctrl ` combinations are often taken by browsers, and I use `alt` for my WM... But who said anything about `ctrl` + `enter` :sweat_smile:

**Comment by mendelmaleh** [comment]
If you meant my first comment, I meant just `enter` with no modifier

**Comment by briano1905** [comment]
Hi I appreciate your contribution but have you tried Tab > Enter ?

**Comment by mendelmaleh** [comment]
Ah well I like overcomplicated solutions xD

**Pull request closed without merging**
