### PR TITLE
Config page

### PR DESCRIPTION
**Pull request by Miodec**
Similar to the themes page - the config page allows you to access the configuration options without memorising codes and key combos.

Added two classes to every theme so that they can be used without altering the themes files everytime we want to add a new element.

Changed the wpm and acc to lowercase to follow the design of the website.

Added a title to the left wing (time: / word:) to indicate which typing mode is active.

The config page is quite bare, feel free to leave feedback / make changes.

### CODE REVIEW

**Comment by jakergrossman** [comment]
https://github.com/briano1905/typings/blob/d2dc5159d9712b786fa0ad8a1c1da1409f08ba71/main.js#L430-L432

should be wrapped in an if statement:
```JavaScript
if (i !== langs.length - 1) {
      let separator = document.createElement('div');
      separator.setAttribute('class', 'separator');
      separator.innerHTML = '/';
}
```
That way there is no trailing separator.

**Comment by Miodec** [comment]
You're right @jakergrossman. Fixed it, thanks!

**Comment by jakergrossman** [comment]
Is there a reason for all the white space diffs?

**Comment by Miodec** [comment]
It was probably because i made the merge in the online github editor and it might have converted all the whitespace.

**Comment by SeerLite** [comment]
I'm pretty sure the issue here is also the windows CRLF. AFAIK @briano1905 should have configured the repo with `autocrlf` to avoid all these problems.

I'm currently trying to convert this PR with unix2dos too to see what it's about.

**Comment by SeerLite** [comment]
I looked at @Miodec's profile to see if they were still active to see if fixing this was worth the time and... I just discovered @Miodec's monkeytype. I just don't know how I didn't find it sooner!

It's not as minimalistic as typings but it looks pretty good, I might switch to that instead of trying to fix this one haha

**Pull request closed without merging**
